params:
  min_retweet_count: 10
  max_dairy_retweet: 400
  max_dairy_likes: 0
  min_followers_count: 20
  min_followers_extended: 500
  max_friends_count: 5000
  add_followers_count: 300
  mins_sleep: 16
  step_batch: 100
  max_batch: 300
  retweet_tracker: False
  follow_tracker: False
  retweet_watcher: False
  follow_watcher: False

languages:
  - es

words:
  block:
    - sex
    - sexo
    - tetas
    - polla
    - follar
    - verga
    - picha
    - coño
    - mierda
    - politica
    - politics
    - politico
    - Ayuntamiento
    - Diputación
    - Diputacion
    - Detective

track:
  - '#dca'
  - '#dañocerebral'
  - '#ictus'
  - neuropsicologia
  - neurorehabilitacion
  - '#saludsinbulos'
  - '#ffpaciente'

follow:
#  - screen_name: ClinicaNeurodem
#    user_id:     789839119
#  - screen_name: fedaceorg
#    user_id:     264130367
#  - screen_name: NeuroalAlmeria
#    user_id:     808983253550039040
#  - screen_name: CreCeadac
#    user_id:     202976293
#  - screen_name: ictusfederacion
#    user_id:     1965026442
#  - screen_name: seneurologia
#    user_id:     376879469
#  - screen_name: fandace
#    user_id:     1095011748    
